united_states_of_america = {
    'name': "USA",
    'start_resources': [1,3,7,14],
    'player_count_info': [
        [3,8,4,10,21,[[3,2,1,1],[4,2,2,1],[3,4,3,1]]],
        [3,8,3, 7,17,[[4,2,1,1],[5,3,2,1],[3,4,3,1]]],
        [4,4,3, 7,17,[[5,3,2,1],[6,4,3,2],[4,5,4,2]]],
        [5,0,3, 7,15,[[5,4,3,2],[7,5,3,3],[5,6,5,2]]],
        [5,0,3, 6,14,[[7,5,3,2],[9,6,5,3],[6,7,6,3]]]
    ],
    'cities': [
        [1,'seattle',3],
        [1,'portland',3],
        [1,'boise',6],
        [1,'billings',5],
        [1,'cheyenne',5],
        [1,'denver',4],
        [1,'omaha',4],
        [2,'san francisco',5],
        [2,'los angeles',3],
        [2,'san diego',3],
        [2,'phoenix',3],
        [2,'las vegas',6],
        [2,'salt lake city',5],
        [2,'santa fe',8],
        [3,'fargo',3],
        [3,'duluth',4],
        [3,'minneapolis',6],
        [3,'chicago',7],
        [3,'st. louis',5],
        [3,'knoxville',2],
        [3,'cincinnati',6],
        [4,'kansas city',7],
        [4,'oklahoma city',4],
        [4,'dallas',5],
        [4,'houston',3],
        [4,'new orleans',5],
        [4,'memphis',6],
        [4,'birmingham',4],
        [5,'miami',1],
        [5,'tampa',2],
        [5,'jacksonville',4],
        [5,'savannah',3],
        [5,'atlanta',5],
        [5,'raleigh',5],
        [5,'norfolk',2],
        [6,'detroit',5],
        [6,'pittsburgh',5],
        [6,'washington dc',3],
        [6,'philadelphia',2],
        [6,'buffalo',3],
        [6,'new york',3],
        [6,'boston',1]
    ],
    'region_connections': [
        [1,2],
        [1,3],
        [1,4],
        [3,4],
        [3,6],
        [3,5],
        [4,5],
        [5,6]
    ],
    'connections': [
        ['seattle','e','billings',9],
        ['seattle','se','boise',12],
        ['seattle','sw','portland',3],
        ['portland','e','boise',13],
        ['portland','s','san francisco',24],
        ['san francisco','ne','boise',23],
        ['san francisco','e','salt lake city',27],
        ['san francisco','se','las vegas',14],
        ['san francisco','s','los angeles',9],
        ['boise','ne','billings',12],
        ['boise','e','cheyenne',24],
        ['boise','se','salt lake city',8],
        ['las vegas','ne','salt lake city',18],
        ['las vegas','sw','los angeles',9],
        ['las vegas','s','san diego',9],
        ['las vegas','se','phoenix',15],
        ['las vegas','e','santa fe',27],
        ['los angeles','se','san diego',3],
        ['san diego','e','phoenix',14],
        ['salt lake city','e','denver',21],
        ['salt lake city','se','santa fe',28],
        ['phoenix','ne','santa fe',18],
        ['billings','ne','fargo',17],
        ['billings','e','minneapolis',18],
        ['billings','se','cheyenne',9],
        ['cheyenne','ne','minneapolis',18],
        ['cheyenne','e','omaha',14],
        ['cheyenne','s','denver',0],
        ['denver','e','kansas city','16'],
        ['denver','s','santa fe',13],
        ['santa fe','ne','kansas city',16],
        ['santa fe','e','oklahoma city',15],
        ['santa fe','se','dallas',16],
        ['santa fe','s','houston',21],
        ['fargo','ne','duluth',6],
        ['fargo','se','minneapolis',6],
        ['omaha','ne','minneapolis',8],
        ['omaha','se','kansas city',5],
        ['omaha','e','chicago',13],
        ['kansas city','ne','chicago',8],
        ['kansas city','e','st. louis',6],
        ['kansas city','se','memphis',12],
        ['kansas city','sw','oklahoma city',8],
        ['oklahoma city','e','memphis',14],
        ['oklahoma city','s','dallas',3],
        ['dallas','ne','memphis',12],
        ['dallas','se','new orleans',12],
        ['dallas','s','houston',5],
        ['houston','e','new orleans',8],
        ['duluth','se','detroit',15],
        ['duluth','s','chicago',12],
        ['duluth','sw','minneapolis',5],
        ['minneapolis','se','chicago',8],
        ['chicago','ne','detroit',7],
        ['chicago','se','cincinnati',7],
        ['chicago','s','st. louis',10],
        ['st. louis','e','cincinnati',12],
        ['st. louis','se','atlanta',12],
        ['st. louis','s','memphis',7],
        ['memphis','se','birmingham',6],
        ['memphis','s','new orleans',7],
        ['new orleans','ne','birmingham',11],
        ['new orleans','e','jacksonville',16],
        ['birmingham','ne','atlanta',3],
        ['birmingham','se','jacksonville',9],
        ['detroit','e','buffalo',7],
        ['detroit','se','pittsburgh',6],
        ['detroit','s','cincinnati',4],
        ['cincinnati','ne','pittsburgh',7],
        ['cincinnati','se','raleigh',15],
        ['cincinnati','s','knoxville',6],
        ['knoxville','s','atlanta',5],
        ['atlanta','ne','raleigh',7],
        ['atlanta','se','savannah',7],
        ['tampa','ne','jacksonville',4],
        ['tampa','se','miami',4],
        ['buffalo','se','new york',8],
        ['buffalo','s','pittsburgh',7],
        ['pittsburgh','se','washington dc',6],
        ['pittsburgh','s','raleigh',7],
        ['savannah','ne','raleigh',7],
        ['savannah','s','jacksonville',0],
        ['washington dc','ne','philadelphia',3],
        ['washington dc','se','norfolk',5],
        ['raleigh','ne','norfolk',3],
        ['philadelphia','ne','new york',0],
        ['new york','ne','boston',3]
    ],
    'automa_start_cities':{
        'e':'san francisco',
        'w':'norfolk',
        'n':'houston',
        's':'duluth',
        'ne':'san diego',
        'sw':'boston',
        'se': 'seattle',
        'nw': 'miami'
    }
}